name: drcc
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - pip
  - qiskit<=1.3.2
  - matplotlib
  - notebook
  - numpy<2.0
  - pandas
  - tqdm
  - ipywidgets
  - pylatexenc
  - msal
  - joblib
  - anytree
  - seaborn
  - graphviz
  - pdoc
  - scikit-learn
  - pip:
    - mthree>=2.6.3
    - qiskit-ibm-runtime<=0.36.1
    - qiskit-algorithms<=0.3.1
    - qiskit-optimization>=0.6.1
    - qiskit-ibm_transpiler
    - qiskit-aer<=0.16
    - openpyxl>=3.1.4